<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Qrcodes\Module'                        => __DIR__ . '/Module.php',
    'Qrcodes\Controller\IndexController' => __DIR__ . '/src/Qrcodes/Controller/IndexController.php',
    'QrcodesTest\Framework\TestCase'        => __DIR__ . '/tests/Qrcodes/Framework/TestCase.php',
    'QrcodesTest\SampleTest'                => __DIR__ . '/tests/Qrcodes/SampleTest.php',
);
